layout_spectrum: 0.3625776
typography_spectrum: 0
color:
  saturation: 0.2096774
  brandStrength: 0.4862028
  lightness: 0.2007169
  rhythmicContrast: 0.6164874
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: yicreative art
